class SeedDefaultCards < ActiveRecord::Migration
  def change
    id = CardPack.where(:name=>"Standard").first.id
    Card.create(:word=>"The gays", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"An oversized lollipop", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"African children", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"An asymmetric boob job", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Bingeing and purging", :word_type => 0, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Mexican", :before=>"The hardworking", :word_type => 1, :card_pack_id => id)
    Card.create(:word=>"An oedipus complex", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"A tiny horse", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Boogers", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Penis envy", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Barack Obama", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"My humps", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"The Tempur-Pedic Swedish Sleep System", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Scientology", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:before => "Dry", :word=>"heave", :word_type => 0, :card_pack_id => id)
    Card.create(:word=>"Skeletor", :word_type => 1, :card_pack_id => id)
    Card.create(:word=>"Darth Vader", :word_type => 1, :card_pack_id => id)
    Card.create(:word=>"Figgy pudding", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Advice from a wise, old black man", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Five-Dollar Footlongs", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Elderly Japanese men", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Free samples", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Estrogen", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Sexual tension", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Famine", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"A stray pube", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Men", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Heartwarming orphans", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Genital piercings", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"A bag of magic beans", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Repression", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Prance", :word_type => 0, :card_pack_id => id)
    Card.create(:word=>"My relationship status", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Overcompensation", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Peeing a little bit", :word_type => 0, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Pooping back and forth. Forever.", :word_type => 0, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Eat all the cookies before the AIDS bake-sale", :word_type => 0, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Testicular torsion", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"The Devil himself", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"The World of Warcraft", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Dick Cheney", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"MechaHitler", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Being fabulous", :word_type => 0, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Pictures of boobs", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"A gentle caress of the inner thigh", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"The Amish", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Pabst blue Ribbon", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Lance Armstrong's missing testicle", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Pedophiles", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"The Pope", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Flying sex snakes", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Emma Watson", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Sexy pillow fights", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Another goddamn vamipre movie", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Cybernetic enhancements", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Civilian casualties", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Scrubbing under the folds", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"The female orgasm", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Bitch", :word_type => 1, :card_pack_id => id)
    Card.create(:word=>"The Boy Scouts of America", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Auschwitz", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:before => "Finger", :word=>"paint", :word_type => 0, :card_pack_id => id)
    Card.create(:word=>"The Care Bear Stare", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"The Jews", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Being marginalized", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"The Blood of Christ", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Dead parents", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"The art of seduction", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Dying of dysentery", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Mr. Clean, right behind you", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"The Virginia Tech Massacare", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Jewish fraternities", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Hot pockets", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Natalie Portman", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Agriculture", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Judge Judy", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Surprise sex!", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"The homosexual agenda", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"The Trail of Tears", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"An M. Night Shyamalan plot twist", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Funky fresh rhymes", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"The light of billion suns", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Amputees", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Throw", :after=> "a virgin into a volcano", :word_type => 0, :card_pack_id => id)
    Card.create(:word=>"Italians", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Explosions", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"A good sniff", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Destroy", :after => "the evidence", :word_type => 0, :card_pack_id => id)
    Card.create(:word=>"Children on leashes", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Catapults", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"One trillion dollars", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Establishing dominance", :word_type => 0, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Die", :word_type => 0, :card_pack_id => id)
    Card.create(:word=>"Silence", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Grow", :after => "a pair", :word_type => 0, :card_pack_id => id)
    Card.create(:word=>"YOU MUST CONSTRUCT ADDITIONAL PYLONS", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Justin Bieber", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"The Holy Bible", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Balls", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Praying the gay away", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Teenage pregnancy", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"German dungeon porn", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"The invisible hand", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"My inner demons", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Powerful thighs", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Getting naked and watching Nickelodean", :word_type => 0, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Crippling debt", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Kamikaze pilots", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Teach", :after => "a robot to love", :word_type => 0, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Police brutality", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Horse meat", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"All-you-can-eat shrimp for $4.99", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Heteronomativity", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Michael Jackson", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"A really cool hat", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Copping a feel", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Crystal meth", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Shapeshifters", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Finger", :word_type => 0, :card_pack_id => id)
    Card.create(:word=>"A disappointing birthday party", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Dental dams", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"My soul", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"The unstoppable tide of Islam", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"The chronic", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Eugenics", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Synergistic management solutions", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"RoboCop", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Serfdom", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Stephen Hawking talking dirty", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Tangled Slinkys", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Fiery poops", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Public ridicule", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"That thing that electrocutes your abs", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Picking up girls at the abortion clinic", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Object permenance", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"GoGurt", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Lockjaw", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Attitude", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Passable transvestites", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Wet dreams", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"The Dance of the Sugar Plum Fairy", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Fire", :after => "off a rifle into the air while balls deep in a squealing hog", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Panda sex", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Necrophilia", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:before => "Grave", :word=>"rob", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"A bleached asshole", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Muhammad (praise be unto him)", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Multiple stab wounds", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Stranger danger", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"A monkey smoking a cigar", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Smegma", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"A live studio audience", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Make", :after => "a pouty face", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"The violation of our most basic human rights", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Unfathomable stupidity", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Sunshine and rainbows", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Whip", :after => "it out", :word_type => 0, :card_pack_id => id)
    Card.create(:word=>"The token minority", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"The terrorists", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"The Three-Fifths compromise", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"A snapping turtle biting the tip of your penis", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Vehicular manslaughter", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"The Great Depression", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Emotions", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word => "Get", :after=>"so angry you pop a boner", :word_type => 0, :card_pack_id => id)
    Card.create(:word=>"Same-sex ice dancing", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"An M16 assault rifle", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Man meat", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Incest", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:before=>"David Bowie", :word=>"fly", :after=> "in on a tiger made of lightning", :word_type => 0, :card_pack_id => id)
    Card.create(:before => "Flightless ", :word=>"bird", :word_type => 1, :card_pack_id => id)
    Card.create(:word => "Do", :after=>"the right thing", :word_type => 0, :card_pack_id => id)
    Card.create(:word=>"When you fart and a little bit comes out", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Frolick", :word_type => 0, :card_pack_id => id)
    Card.create(:word=>"Being a dick to children", :word_type => 0, :card_pack_id => id, :plain => true)
    Card.create(:before => "Poopy", :word=>"diaper", :word_type => 1, :card_pack_id => id)
    Card.create(:word=>"Tickle", :after => "Sean Hannity, even after he tells you to stop", :word_type => 0, :card_pack_id => id)
    Card.create(:before=>"Raptor", :word=>"attack", :word_type => 1, :card_pack_id => id)
    Card.create(:word=>"Swoop", :word_type => 0, :card_pack_id => id)
    Card.create(:word=>"Conceal", :after=>"a boner", :word_type => 0, :card_pack_id => id)
    Card.create(:word=>"Full frontal nudity", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Vigorous jazz hands", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Nipple blades", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"A bitch slap", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Michelle Obama's arms", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Mouth herpes", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"A robust mongoloid", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Mutually-assured destruction", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"The Rapture", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Road head", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Stalin", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Lactation", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Hurricane Katrina", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"The true meaning of Christmas", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Self-loathing", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"A brain tumor", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:before => "Dead", :word=>"baby", :word_type => 1, :card_pack_id => id)
    Card.create(:word=>"New Age music", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"A thermonuclear detonation", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Goose", :word_type => 1, :card_pack_id => id)
    Card.create(:word=>"Kanye West", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"God", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Become", :after=>"a blueberry", :word_type => 0, :card_pack_id => id)
    Card.create(:word=>"Harry Potter erotica", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Kids with ass cancer", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Lumberjack fantasies", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"The American Dream", :word_type => 1, :card_pack_id => id, :plain => true)
    Card.create(:word=>"Puberty", :word_type => 1, :card_pack_id => id, :plain => true)
  end
end
