class FixBadPrompts < ActiveRecord::Migration
  def change
    id = CardPack.where(:name=>"Standard").first.id
    Prompt.delete_all(:card_pack_id => id)
    Prompt.create(:text => "____? There's an app for that.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "Maybe she's born with it. Maybe it's ____.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "In L.A. County Jail, word is you can trade 200 cigarettes for ____.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "After the earthquake, Sean Penn brought ____ to the people of Haiti.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "Next on ESPN2, the World Series of ____.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "Step 1: ____. Step 2: ____. Step 3: Profit.", :card_pack_id => id, :blanks => 2)
    Prompt.create(:text => "Life for American Indians was forever changed when the White Man introduced them to ____.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "What's the next superhero/sidekick duo?", :card_pack_id => id, :blanks => 2)
    Prompt.create(:text => "What's that sound?", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "What ended my last relationship?", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "What is Batman's guilty pleasure?", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "What's a girl's best friend?", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "What does Dick Cheney prefer?", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "What's the most emo?", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "What are my parents hiding from me?", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "What will always get you laid?", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "What did I bring back from Mexico?", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "What don't you want to find in your Chinese food?", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "What will I bring back in time to convince people that I am a powerful wizard?", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "How am I maintaining my relationship status?", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "What gives me uncontrollable gas?", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "What do old people smell like? ", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "What's my secret power?", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "What's there a ton of in heaven?", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "What would grandma find disturbing, yet oddly charming?", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "What did the U.S. airdrop to the children of Afghanistan?", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "What helps Obama unwind?", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "What did Vin Diesel eat for dinner?", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "Why am I sticky?", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "What gets better with age?", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "What's the crustiest?", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "What's Teach for America using to inspire inner city students to succeed?", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "Make a haiku.", :card_pack_id => id, :blanks => 3)
    Prompt.create(:text => "Why do I hurt all over?", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "What am I giving up for Lent?", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "What's my anti-drug?", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "What never fails to liven up the party?", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "What's the new fad diet?", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "I got 99 problems but ____ ain't one.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "TSA guidelines now prohibit ____ on airplanes.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "MTV's new reality show features eight washed-up celebrities living with ____.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "I drink to forget ____.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "I'm sorry, Professor, but I couldn't complete my homework because of ____.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of ____.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "Alternative medicine is now embracing the curative powers of ____.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "Anthropologists have recently discovered a primitive tribe that worships ____.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "It's a pity that kids these days are all getting involved with ____.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "____. That's how I want to die.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "In the new Disney Channel Original Movie, Hannah Montana struggles with ____ for the first time.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "I wish I hadn't lost the instruction manual for ____.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "Instead of coal, Santa now gives the bad children ____.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "In 1,000 years, when paper money is but a distant memory, ____ will be our currency.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "A romantic, candlelit dinner would be incomplete without ____.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "Next from J.K. Rowling: Harry Potter and the Chamber of ____.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "____. Betcha can't have just one!", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "White people like ____.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "____. High five, bro.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "During sex, I like to think about ____.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "BILLY MAYS HERE FOR ____.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "When I'm in prison, I'll have ____ smuggled in.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "When I am the President of the United States, I will create the Department of ____.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "Major League Baseball has banned ____ for giving players an unfair advantage.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "When I am a billionare, I shall erect a 50-foot statue to commemorate ____.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "____. It's a trap!", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "Coming to Broadway this season, ____: The Musical.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "After Hurricane Katrina, Sean Penn brought ____ to all the people of New Orleans.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "Due to a PR fiasco, Walmart no longer offers ____.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "But before I kill you, Mr. Bond, I must show you ____.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "When Pharaoh remained unmoved, Moses called down a plague of ____.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "The class field trip was completely ruined by ____.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "In Michael Jackson's final moments, he thought about ____.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on ____.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "Studies show that lab rats navigate mazes 50% faster after being exposed to ____.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "I do not know with which weapons World War III will be fought, but World War IV will be fought with ____.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "Life was difficult for cavemen before ____.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "____: Good to the last drop.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "____: kid-tested, mother-approved.", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "And the Academy Award for ____ goes to ____.", :card_pack_id => id, :blanks => 2)
    Prompt.create(:text => "For my next trick, I will pull ____ out of ____.", :card_pack_id => id, :blanks => 2)
    Prompt.create(:text => "____ is a slippery slope that leads to ____.", :card_pack_id => id, :blanks => 2)
    Prompt.create(:text => "In M. Night Shyamalan's new movie, Bruce Willis discovers that ____ had really been ____ all along.", :card_pack_id => id, :blanks => 2)
    Prompt.create(:text => "In a world ravaged by ____, our only solace is ____.", :card_pack_id => id, :blanks => 2)
    Prompt.create(:text => "In his new summer comedy, Rob Schneider is ____ trapped in the body of ____.", :card_pack_id => id, :blanks => 2)
    Prompt.create(:text => "I never truly understood ____ until I encountered ____.", :card_pack_id => id, :blanks => 2)
    Prompt.create(:text => "When I was tripping on acid, ____ turned into ____.", :card_pack_id => id, :blanks => 2)
    Prompt.create(:text => "That's right, I killed ____. How, you ask? ____.", :card_pack_id => id, :blanks => 2)
    Prompt.create(:text => "____ + ____ = ____.", :card_pack_id => id, :blanks => 3)
    Prompt.create(:text => "Why can't I sleep at night?", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "What's that smell?", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "Who stole the cookies from the cookie jar?", :card_pack_id => id, :blanks => 1)
    Prompt.create(:text => "What's the next superhero?", :card_pack_id => id, :blanks => 1)
  end
end
