class SeedDefaultCards2 < ActiveRecord::Migration
  def change
    id = CardPack.where(:name => "Standard").first.id
    Card.create(:word => "Sweet, sweet vengeance", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Wink", :after=>"at old people", :word_type => 0, :card_pack_id => id)
    Card.create(:word => "The taint; the grundle; the fleshy fun-bridge", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Oompa-Loompas", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Authentic Mexican cuisine", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Preteens", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "The Little Engine That Could", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Guys who don't call", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Erectile dysfucntion", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Parting the Red Sea", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Rush Limbaugh's soft, shitt body", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "A saxophone solo", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Land mines", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Capturing Newt Gingrich and forcing him to dance in a monkey suit", :word_type => 0, :plain => true, :card_pack_id => id)
    Card.create(:word => "Me time", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Nickelback", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Vigilante justice", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "The South", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Opposable thumbs", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Ghosts", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Alchoholism", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Poorly-timed Holocaust jokes", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Inappropriate yodeling", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Battlefield amputations", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Exactly what you'd expect", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "A time travel paradox", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "AXE Body Spray", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:before => "Actually", :word=>"take", :after=>"candy from a baby", :word_type => 0, :card_pack_id => id)
    Card.create(:word => "Leave", :after=>"an awkward voicemail", :word_type => 1, :card_pack_id => id)
    Card.create(:word => "A sassy black woman", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Being a motherfucking sorcerer", :word_type => 0, :plain => true, :card_pack_id => id)
    Card.create(:word => "A mopey zoo lion", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "A murder most foul", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "A falcon with a cap on its head", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Farting and walking away", :word_type => 0, :plain => true, :card_pack_id => id)
    Card.create(:word => "A mating display", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "A Chinese gymnastics team", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Friction", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Asians who aren't good at math", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Fear itself", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "A can of whoop-ass", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Yeast", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Lunchables", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Lick", :after =>"things to claim them as your own", :word_type => 0, :card_pack_id => id)
    Card.create(:word => "Vikings", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "The Kool-Aid Man", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Hot cheese", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Nicolas Cage", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "A defective condom", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "The inevitable heat death of the universe", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Republicans", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "William Shatner", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Tentacle porn", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Sperm whales", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Lady Gaga", :word_type => 1, :plain => true, :card_pack_id => id)
    Card.create(:word => "Chunks of dead prostitute", :word_type => 1, :plain => true, :card_pack_id => id)
  end
end
